### ISSUE TITLE
Add travis CI to the project

### ISSUE THREAD

**Issue by stephanenicolas** [bjoernQ/unmock-plugin#54]
Here is the android doc : https://docs.travis-ci.com/user/languages/android/
The setup instructions are here: https://docs.travis-ci.com/user/tutorial/

The `.travis.yml` file will look like this:
```yml
language: android

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

script:
  - ./gradlew clean install
  - ./gradlew -b example/build.gradle assembleDebug

```
